# SPDX-FileCopyrightText: 2024 Andreas Fehlner
#
# SPDX-License-Identifier: MIT

name: Pipeline including publishing

on: 
  schedule:
    # Run weekly on Monday 00:00
    - cron:  '00 00 * * MON'
  push:
    branches: [master,"*"]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build distribution with poetry
    runs-on: ubuntu-latest
    outputs:
      hash: ${{ steps.hash.outputs.hash }}
  
    permissions:
        id-token: write  # IMPORTANT: mandatory for trusted publishing
  
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Poetry / Build Package
      run: |
        curl -sSL https://install.python-poetry.org | python3 - 
        poetry install
        poetry build

    - name: pytest (pytorch stable)
      continue-on-error: true  # TODO change to xfail?
      run: poetry run pytest -ra

    - name: pytest (pytorch nightly)
      # Sometimes errors like that "Because no versions of torchvision match >0.20.0.dev20240706+cpu,<0.21.0
      # and torchvision (0.20.0.dev20240706+cpu) depends on torch (2.5.0.dev20240706), torchvision (>=0.20.0.dev20240706+cpu,<0.21.0) requires torch (2.5.0.dev20240706).
      # So, because power-spherical depends on both torch (>=2.5.0.dev20240707+cpu,<3.0.0) and torchvision (^0.20.0.dev20240706+cpu), version solving failed."
      continue-on-error: true 
      run: |
        poetry add onnxscript
        poetry source add --priority explicit pytorch https://download.pytorch.org/whl/nightly/cpu
        poetry add --source pytorch torch torchvision        
        poetry run pytest -ravvv
    
    - name: Store the distribution packages
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    # Generate hashes used for provenance.
    - name: generate hash
      id: hash
      run: cd dist && echo "hash=$(sha256sum * | base64 -w0)" >> $GITHUB_OUTPUT
    - name: Print variable
      run: echo "Hash $GITHUB_OUTPUT"    

  publish-to-testpypi: # To test the upload path to testpypi, build the wheel with a version tag including the current date
    name: Publish to TestPyPI    
    needs:
      - build
    if: (github.ref == 'refs/heads/master') || ${{ github.event.label.name == 'testpypi' }}
   
    runs-on: ubuntu-latest

    environment:
      name: testpypi
      url: https://test.pypi.org/p/power-spherical

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:

    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install Poetry / Build Package
      run: |
        curl -sSL https://install.python-poetry.org | python3 - 
        poetry install
        todays_date=$(date +"%Y%m%d")
        echo $(todays_date)
        currversion=$(poetry version -s)
        echo $(currversion)
        currversion=$(currversion + ".dev" + $(todays_date))
        echo $(currversion)
        poetry version currversion
        poetry build
      shell: bash
        
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/


  publish-to-pypi:
    name: Publish to PyPI
    if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    needs:
    - build
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/power-spherical

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1      

  provenance:
    name: Generate SLSA provenance data
    needs: [build]
    permissions:
      actions: read # Needed for detection of GitHub Actions environment.
      id-token: write # Needed for provenance signing and ID
      contents: write  # Needed for release uploads, https://github.com/slsa-framework/slsa-github-generator/issues/2044 :( 
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: '${{ needs.build.outputs.hash }}'
      # Upload provenance to a new release
      upload-assets: true      


  github-release:
    name: >-
      Sign with Sigstore and upload them to GitHub Release
    needs:
    - build

    runs-on: ubuntu-latest

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases
      id-token: write  # IMPORTANT: mandatory for sigstore

    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Sign the dists with Sigstore
      uses: sigstore/gh-action-sigstore-python@v2.1.1
      with:
        inputs: >-
          ./dist/*.tar.gz
          ./dist/*.whl

    - name: Rename files # to match new file extension https://github.com/sigstore/sigstore-python/blob/main/CHANGELOG.md#changed
      run: |
        sudo apt install mmv 
        mmv "./dist/*.sigstore" ./dist/#1.sigstore.json
  
    # - name: Create GitHub Release
    #   release is created by the UI
    - name: Upload artifact signatures to GitHub Release
      if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
      env:
        GITHUB_TOKEN: ${{ github.token }}
      # Upload to GitHub Release using the `gh` CLI.
      # `dist/` contains the built packages, and the
      # sigstore-produced signatures and certificates.
      run: >-
        gh release upload
        '${{ github.ref_name }}' dist/** 
        --repo '${{ github.repository }}'                
        